FROM node:18 AS deps
WORKDIR /app

# Copy only package.json first
COPY package*.json ./
COPY prisma ./prisma

RUN npm install --legacy-peer-deps

# ------------------------
FROM node:20 AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npx prisma generate 
RUN npm run build --legacy-peer-deps

# ------------------------
FROM node:20 AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY package*.json ./

EXPOSE 3000
CMD ["npm", "start"]
